[bot][devbox8][indranilnandy][Wed Feb 26 03:41:57 PM IST 2025] Remote updated with latest

diff --git a/task/scm/gh-script/gh-script.yaml b/task/scm/gh-script/gh-script.yaml
--- a/task/scm/gh-script/gh-script.yaml
+++ b/task/scm/gh-script/gh-script.yaml
@@ -165,10 +165,11 @@ spec:
         git config --global user.name "$(params.GIT_USER_NAME)"
 
         echo -e "Script parameters:"
-        for x in $@; do
+        # for i in "$@"; do echo $i ; done
+        for x in "$@"; do
             echo -e "\t$x"
-            eval $x || {
-                echo -e $x: Invalid command
+            eval "$x" || {
+                echo -e "$x": Invalid command
                 exit 1
             }
         done
